title: Voidstack
description: Start from void. Stack your skills. Reach root.
baseurl: "" 
url: "https://v0idstack.github.io"

remote_theme: pages-themes/minimal@v0.2.0

layout: default

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

remote_theme: pages-themes/hacker@v0.2.0